name: gofilesdk
description: Unofficial GoFile SDK for Dart and Flutter
version: 0.0.2
repository: https://github.com/radenrishwan/gofilesdk

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
